### ISSUE TITLE
La fermeture de ticket ne fonctionne pas comme convenue

### ISSUE THREAD

**Issue by Deo-Favente** [MarketDiscord/E-Bot#9]
Fermer un ticket, c'est retirer l'utilisateur qui l'a ouvert de ce dernier pour laisser le staff en discuter sans lui ou l'archiver. On a convenu que tant qu'on ne serait pas débordés, on ne supprimerais aucun channel ticket contenant une commande afin d'avoir d'éventuelles preuves en cas de problème. Je pense tout de même qu'on peux rajouter cette fonctionnalité de supprimer pour les tickets ouverts inutilement, mais il faut alors rajouter un vrai bouton close qui fait ce qu'on lui demande.

**Comment by Thesuicidaul** [comment]
cela me parais pas trop logique car si un gars crée un ticket sans faire exprès flemme de devoir le fermer nous
et a la fin d'une commande on a juste qu'a le kick du channel genre et c'est bon

**Comment by Deo-Favente** [comment]
> cela me parais pas trop logique car si un gars crée un ticket sans faire exprès flemme de devoir le fermer nous et a la fin d'une commande on a juste qu'a le kick du channel genre et c'est bon
@Thesuicidaul 
Bah justement bozo je demande une commande pour le kick du channel

**Comment by Deo-Favente** [comment]
Surtout que supprimer un ticket c'est une décision d'un admin, alors que fermer le ticket l'user peut le faire lui si il ne veux plus du ticket

**Comment by Thesuicidaul** [comment]
mais non en gros la si le gars lance un ticket sans faire exprès il peut fermer le ticket , et a la fin on le kick avant qu'il suprime le ticket

**Comment by Deo-Favente** [comment]
Je trouve trop dangereux de laisser la permission au client de supprimer un channel, surtout s'il contient des informations qui pourraient être compromettantes pour lui. Close, delete et archive ça me semble très bien comme bouton, sur @walibicraft on a jamais eu de problème avec ça

**Comment by Thesuicidaul** [comment]
ok ok
